### ISSUE TITLE
Does this work with i18n?

### ISSUE THREAD

**Issue by simplenotezy** [LuXDAmore/nuxt-apis-to-file#2]
I use nuxtServerInit and the response for both danish and english are different. Does it work with i18n?

Also, another problem I faced with nuxtServerInit and page-generation, is that the request is called on EVERY page, causing a much longer "generate" process, and also unnecessary load on server. I implemented my own workaround, to serve nuxtServerInit with "payload" data to avoid this, but I was wondering if this plugin already took care of that as well?

**Comment by LuXDAmore** [comment]
I'm sorry, for my late reply @simplenotezy 😞 

___

This module is a **buildModule**, so it's called only during the build phase (nuxt >= v2.9).

I have never used it in a `generate context`, but (i think), nuxt is gonna request it only one time (during the build process).. Then the static data is served and cached by webpack for every `generated page`..
So, it shouldn't take longer during the `generate process`.

As for the _i18n_ (if i have intended correctly), there are no problems about that..
In the requests array, you could pass two endpoints (maybe one per language), then you can dynamically load them.

ex.
```javascript

// nuxt-config
const options = {
    requests: [
        {
            endpoint: 'https://your-api-url/en',
            field: 'en',
        },
        {
            endpoint: 'https://your-api-url/da',
            field: 'da',
        },
    ],
};

// store or wherever you want
const getFile = () => import(
    '~/apis-to-file/data.json'
).then(
    m => m.default || m
);

// store
export const actions = {
    async getDataFromFile(
        { commit }
    ) {

        let en = {}
            , da = {}
        ;

        try {

            const { en, da } = await getFile();

            if( en )
                en = en;

            if( da )
                da = da;

        } catch( e ) {

            console.error(
                {
                    e,
                }
            );

        }

        commit(
            'languages/SET_EN',
            en,
            {
                root: true,
            }
        );

        commit(
            'languages/SET_DA',
            da,
            {
                root: true,
            }
        );

    }
};

```

But much depends on how you have to use the static data..

Hope this example could help you 😄 
Let me know and keep me informed if you need more details or if you are able to use this module. 

Hope this helps!
Let me know and keep me informed if you need more details or if you are able to use this module.  🤞
